### ISSUE TITLE
na_ontap_info throws an unexpected error

### ISSUE THREAD

**Issue by nikolaykanov** [ansible-collections/netapp#57]
##### SUMMARY

When I try to use na_ontap_info in a playbook, it always fails with an unexpected error 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

na_ontap_info 

##### ANSIBLE VERSION

```paste below
ansible 2.9.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 50
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

NetApp Release 9.3P14: Wed Jul 10 14:38:46 UTC 2019

##### STEPS TO REPRODUCE

```yaml
  - name: this fails, open a bug when you get some time
    na_ontap_info:
      username: "{{ env_vars.netapp.username }}"
      password: "{{ env_vars.netapp.password }}"
      hostname: "{{ env_vars.netapp.hostname }}"
      validate_certs: no
    register: command_out
```

##### EXPECTED RESULTS

Get ontap info

##### ACTUAL RESULTS

```paste below
TASK [this fails, open a bug when you get some time] ****************************************************************************************************************************************
task path: /etc/ansible/nkanov/netapp.yml:14
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1600417818.82-62050145132658 `" && echo ansible-tmp-1600417818.82-62050145132658="` echo /root/.ansible/tmp/ansible-tmp-1600417818.82-62050145132658 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/netapp/ontap/plugins/modules/na_ontap_info.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-9883BphQUU/tmp0gKihE TO /root/.ansible/tmp/ansible-tmp-1600417818.82-62050145132658/AnsiballZ_na_ontap_info.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1600417818.82-62050145132658/ /root/.ansible/tmp/ansible-tmp-1600417818.82-62050145132658/AnsiballZ_na_ontap_info.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1600417818.82-62050145132658/AnsiballZ_na_ontap_info.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1600417818.82-62050145132658/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1600417818.82-62050145132658/AnsiballZ_na_ontap_info.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1600417818.82-62050145132658/AnsiballZ_na_ontap_info.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1600417818.82-62050145132658/AnsiballZ_na_ontap_info.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.netapp.ontap.plugins.modules.na_ontap_info', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_na_ontap_info_payload_zoEHA1/ansible_na_ontap_info_payload.zip/ansible_collections/netapp/ontap/plugins/modules/na_ontap_info.py", line 1700, in <module>
  File "/tmp/ansible_na_ontap_info_payload_zoEHA1/ansible_na_ontap_info_payload.zip/ansible_collections/netapp/ontap/plugins/modules/na_ontap_info.py", line 1692, in main
  File "/tmp/ansible_na_ontap_info_payload_zoEHA1/ansible_na_ontap_info_payload.zip/ansible_collections/netapp/ontap/plugins/modules/na_ontap_info.py", line 1478, in get_all
  File "/tmp/ansible_na_ontap_info_payload_zoEHA1/ansible_na_ontap_info_payload.zip/ansible_collections/netapp/ontap/plugins/modules/na_ontap_info.py", line 1467, in send_ems_event
  File "/tmp/ansible_na_ontap_info_payload_zoEHA1/ansible_na_ontap_info_payload.zip/ansible_collections/netapp/ontap/plugins/module_utils/netapp.py", line 329, in get_cserver
  File "/tmp/ansible_na_ontap_info_payload_zoEHA1/ansible_na_ontap_info_payload.zip/ansible_collections/netapp/ontap/plugins/module_utils/netapp.py", line 299, in get_cserver_zapi
netapp_lib.api.zapi.zapi.NaApiError: NetApp API failed. Reason - Unexpected error:

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1600417818.82-62050145132658/AnsiballZ_na_ontap_info.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1600417818.82-62050145132658/AnsiballZ_na_ontap_info.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1600417818.82-62050145132658/AnsiballZ_na_ontap_info.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.netapp.ontap.plugins.modules.na_ontap_info', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_na_ontap_info_payload_zoEHA1/ansible_na_ontap_info_payload.zip/ansible_collections/netapp/ontap/plugins/modules/na_ontap_info.py\", line 1700, in <module>\n  File \"/tmp/ansible_na_ontap_info_payload_zoEHA1/ansible_na_ontap_info_payload.zip/ansible_collections/netapp/ontap/plugins/modules/na_ontap_info.py\", line 1692, in main\n  File \"/tmp/ansible_na_ontap_info_payload_zoEHA1/ansible_na_ontap_info_payload.zip/ansible_collections/netapp/ontap/plugins/modules/na_ontap_info.py\", line 1478, in get_all\n  File \"/tmp/ansible_na_ontap_info_payload_zoEHA1/ansible_na_ontap_info_payload.zip/ansible_collections/netapp/ontap/plugins/modules/na_ontap_info.py\", line 1467, in send_ems_event\n  File \"/tmp/ansible_na_ontap_info_payload_zoEHA1/ansible_na_ontap_info_payload.zip/ansible_collections/netapp/ontap/plugins/module_utils/netapp.py\", line 329, in get_cserver\n  File \"/tmp/ansible_na_ontap_info_payload_zoEHA1/ansible_na_ontap_info_payload.zip/ansible_collections/netapp/ontap/plugins/module_utils/netapp.py\", line 299, in get_cserver_zapi\nnetapp_lib.api.zapi.zapi.NaApiError: NetApp API failed. Reason - Unexpected error:\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP **********************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```

**Comment by lonico** [comment]
Unexpected error generally indicates a connection issue.  This is explained at
https://netapp.io/2019/08/05/dealing-with-the-unexpected/

We already updated netapp-lib to provide a better error reporting.  The change went into version 2019.12.19 of netapp-lib.  Instead of reporting "Unexpected Error", it now shows a specific exception.

We also improved how the error is handled in our modules.  This change went into the 20.9.0 ONTAP collection.  But you'll still need to address the root cause.

One possibility is that you need to add `https: true` in you playbook,

**Comment by nikolaykanov** [comment]
You were right on both counts. Once I updated netapp-lib, I could see the connection refused error. Enabling https fixed the problem.
