### ISSUE TITLE
azure_rm_netapp_volume generates 'NoneType' object is not subscriptable on line 253

### ISSUE THREAD

**Issue by Chaffelson** [ansible-collections/netapp#77]
##### SUMMARY

Use of this module always fails due to python type issues

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_netapp_volume

##### ANSIBLE VERSION

```paste below
ansible 2.10.3
  config file = /ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.7 (default, Jul 19 2020, 03:57:54) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_SSH_RETRIES(/ansible/ansible.cfg) = 10
COLLECTIONS_PATHS(/ansible/ansible.cfg) = ['/ansible/collections']
DEFAULT_CALLBACK_WHITELIST(/ansible/ansible.cfg) = ['profile_tasks']
DEFAULT_HOST_LIST(/ansible/ansible.cfg) = ['/ansible/inventories']
DEFAULT_ROLES_PATH(/ansible/ansible.cfg) = ['/ansible/roles']
ENABLE_TASK_DEBUGGER(/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT

Running in alpine linux docker container on osx

##### STEPS TO REPRODUCE

```yaml
- name: Handle Azure NetApp Volume
  register: _fef0_az_netapp_vol_info
  netapp.azure.azure_rm_netapp_volume:
    resource_group: "{{ fef0_metagroup_name }}"
    account_name: "{{ fef0_netapp_account_name }}"
    pool_name: "{{ fef0_netapp_pool_name }}"
    name: "{{ fef0_netapp_vol_name }}"
    state: "{{ _fef0_state }}"
    location: "{{ fef0_az_region }}"
    file_path: "{{ fef0_namespace }}"
    virtual_network: "{{ fef0_vpcvnet_name }}"
    subnet_id: "{{ _fef0_az_netapp_subnet_uri }}"
    service_level: Standard
    size: 500
```

##### EXPECTED RESULTS

Volume is created

##### ACTUAL RESULTS

```paste below
TASK [debug] ********************************************************************************************************************************
task path: /ansible/1x3_storage.yml:104
Thursday 17 December 2020  17:57:30 +0000 (0:00:03.048)       0:03:05.036 ***** 
ok: [localhost] => {
    "msg": "fef0-az-test-rmgp - fef0-az-test-netapp-accnt - fef0-az-test-netapp-pool - fef0-az-test-netapp-data - fef0-az-test-net - /subscriptions/d03b96f5-4d5b-4bb6-be9b-1e0ab5086602/resourceGroups/fef0-az-test-rmgp/providers/Microsoft.Network/virtualNetworks/fef0-az-test-net/subnets/fef0-az-test-netapp-sbnt"
}


TASK [Handle Azure NetApp Volume] ***********************************************************************************************************
task path: /ansible/1x3_storage.yml:109
Thursday 17 December 2020  17:58:17 +0000 (0:00:46.430)       0:03:51.678 ***** 
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1608227897.4657242-1086-97315431146798 `" && echo ansible-tmp-1608227897.4657242-1086-97315431146798="` echo /root/.ansible/tmp/ansible-tmp-1608227897.4657242-1086-97315431146798 `" ) && sleep 0'
Using module file /ansible/collections/ansible_collections/netapp/azure/plugins/modules/azure_rm_netapp_volume.py
<localhost> PUT /root/.ansible/tmp/ansible-local-1gpemvpe1/tmp3irpvqdr TO /root/.ansible/tmp/ansible-tmp-1608227897.4657242-1086-97315431146798/AnsiballZ_azure_rm_netapp_volume.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1608227897.4657242-1086-97315431146798/ /root/.ansible/tmp/ansible-tmp-1608227897.4657242-1086-97315431146798/AnsiballZ_azure_rm_netapp_volume.py && sleep 0'
<localhost> EXEC /bin/sh -c 'ANSIBLE_HOST_KEY_CHECKING=False AWS_REGION=eu-west-1 /usr/bin/python3.7 /root/.ansible/tmp/ansible-tmp-1608227897.4657242-1086-97315431146798/AnsiballZ_azure_rm_netapp_volume.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1608227897.4657242-1086-97315431146798/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1608227897.4657242-1086-97315431146798/AnsiballZ_azure_rm_netapp_volume.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1608227897.4657242-1086-97315431146798/AnsiballZ_azure_rm_netapp_volume.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1608227897.4657242-1086-97315431146798/AnsiballZ_azure_rm_netapp_volume.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.netapp.azure.plugins.modules.azure_rm_netapp_volume', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_netapp.azure.azure_rm_netapp_volume_payload_lb9lepd2/ansible_netapp.azure.azure_rm_netapp_volume_payload.zip/ansible_collections/netapp/azure/plugins/modules/azure_rm_netapp_volume.py", line 262, in <module>
  File "/tmp/ansible_netapp.azure.azure_rm_netapp_volume_payload_lb9lepd2/ansible_netapp.azure.azure_rm_netapp_volume_payload.zip/ansible_collections/netapp/azure/plugins/modules/azure_rm_netapp_volume.py", line 258, in main
  File "/tmp/ansible_netapp.azure.azure_rm_netapp_volume_payload_lb9lepd2/ansible_netapp.azure.azure_rm_netapp_volume_payload.zip/ansible_collections/netapp/azure/plugins/modules/azure_rm_netapp_volume.py", line 178, in __init__
  File "/tmp/ansible_netapp.azure.azure_rm_netapp_volume_payload_lb9lepd2/ansible_netapp.azure.azure_rm_netapp_volume_payload.zip/ansible_collections/netapp/azure/plugins/module_utils/azure_rm_netapp_common.py", line 23, in __init__
  File "/tmp/ansible_netapp.azure.azure_rm_netapp_volume_payload_lb9lepd2/ansible_netapp.azure.azure_rm_netapp_volume_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 441, in __init__
  File "/tmp/ansible_netapp.azure.azure_rm_netapp_volume_payload_lb9lepd2/ansible_netapp.azure.azure_rm_netapp_volume_payload.zip/ansible_collections/netapp/azure/plugins/modules/azure_rm_netapp_volume.py", line 253, in exec_module
TypeError: 'NoneType' object is not subscriptable
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1608227897.4657242-1086-97315431146798/AnsiballZ_azure_rm_netapp_volume.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1608227897.4657242-1086-97315431146798/AnsiballZ_azure_rm_netapp_volume.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1608227897.4657242-1086-97315431146798/AnsiballZ_azure_rm_netapp_volume.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.netapp.azure.plugins.modules.azure_rm_netapp_volume', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.7/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.7/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_netapp.azure.azure_rm_netapp_volume_payload_lb9lepd2/ansible_netapp.azure.azure_rm_netapp_volume_payload.zip/ansible_collections/netapp/azure/plugins/modules/azure_rm_netapp_volume.py\", line 262, in <module>\n  File \"/tmp/ansible_netapp.azure.azure_rm_netapp_volume_payload_lb9lepd2/ansible_netapp.azure.azure_rm_netapp_volume_payload.zip/ansible_collections/netapp/azure/plugins/modules/azure_rm_netapp_volume.py\", line 258, in main\n  File \"/tmp/ansible_netapp.azure.azure_rm_netapp_volume_payload_lb9lepd2/ansible_netapp.azure.azure_rm_netapp_volume_payload.zip/ansible_collections/netapp/azure/plugins/modules/azure_rm_netapp_volume.py\", line 178, in __init__\n  File \"/tmp/ansible_netapp.azure.azure_rm_netapp_volume_payload_lb9lepd2/ansible_netapp.azure.azure_rm_netapp_volume_payload.zip/ansible_collections/netapp/azure/plugins/module_utils/azure_rm_netapp_common.py\", line 23, in __init__\n  File \"/tmp/ansible_netapp.azure.azure_rm_netapp_volume_payload_lb9lepd2/ansible_netapp.azure.azure_rm_netapp_volume_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 441, in __init__\n  File \"/tmp/ansible_netapp.azure.azure_rm_netapp_volume_payload_lb9lepd2/ansible_netapp.azure.azure_rm_netapp_volume_payload.zip/ansible_collections/netapp/azure/plugins/modules/azure_rm_netapp_volume.py\", line 253, in exec_module\nTypeError: 'NoneType' object is not subscriptable\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```

**Comment by Chaffelson** [comment]
Looks like the volume creation failed to create any mount targets, and thus line 253 is looking for a property that is None

**Comment by lonico** [comment]
Yes, it is an issue when we're trying to read the mount point.  Though the volume should be created anyway, even if the module crashes.
We'll address this ASAP. 
Can you verify that the volume exists, or is it deleted as the mount targets cannot be created?

**Comment by Chaffelson** [comment]
I'm working on creating the volume now, looks like it doesn't like the subnet URI I'm supplying
```
"msg": "Error creating volume fef0-az-test-netapp-data for Azure NetApp account fef0-az-test-netapp-accnt and subnet ID /subscriptions/d03b96f5-4d5b-4bb6-be9b-1e0ab5086602/resourceGroups/fef0-az-test-rmgp/providers/Microsoft.Network/virtualNetworks/fef0-az-test-net/subnets/fef0-az-test-netapp-sbnt: Azure Error: BadRequest\nMessage: SubnetId is in invalid format.\nException Details:\n\tError Code: InvalidSubnet\n\tMessage: SubnetId is in invalid format."
```

**Comment by Chaffelson** [comment]
The description on the property is a little ambiguous:

```
subnet_id:
        description:
            - The Azure Resource URI for a delegated subnet. Must have the delegation Microsoft.NetApp/volumes.
            - Provide name of the subnet ID.
            - Required for create.
        type: str
```

This implies the URI is required in the description, but the property is named 'subnet_id', and then states the Name should be provided. Will try with the name.

**Comment by Chaffelson** [comment]
The volume is created, but with state InvalidId when the URI is supplied FYI

**Comment by lonico** [comment]
We're saying URI in the first line, and name in the second line :(

**Comment by Chaffelson** [comment]
Sounds like the issue then, using the name works.
I'd humbly suggest subnet_id should be renamed to subnet_name for clarity, then put subnet_id in as an alias to provide backwards compatibility for existing users.

**Comment by lonico** [comment]
will do

**Comment by lonico** [comment]
fixed with 5793480ce953b3eb3106b80a9285ca2b08d986de

Targeted for 21.1.0 release.

**Comment by carchi8py** [comment]
This was pushed out in the 21.1.0 release.
