### ISSUE TITLE
azure_rm_netapp_common always attempts to use AzureNetAppFilesManagementClient

### ISSUE THREAD

**Issue by Chaffelson** [ansible-collections/netapp#86]
##### SUMMARY

When using `netapp.azure.azure_rm_netapp_volume` from the Collection of ver 21.2.0 with `azure-mgmt-netapp` ver 1.0.0 it relies on `azure_rm_netapp_common`, which always attempts to use the pre 1.0 `AzureNetAppFilesManagementClient` instead of the new Client `NetAppManagementClient`.

In the same Python environment the command `from azure.mgmt.netapp import NetAppManagementClient` completes successfully, so perhaps the NEW_STYLE switch is not behaving as intended.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_netapp_common

##### ANSIBLE VERSION

```paste below
ansible 2.10.6.post0
  config file = /runner/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.3 (default, Aug 31 2020, 16:03:14) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

```

##### CONFIGURATION

```paste below
ANSIBLE_SSH_RETRIES(/runner/ansible.cfg) = 10
COLLECTIONS_PATHS(/runner/ansible.cfg) = ['/home/runner/.ansible/collections', '/runner/project/ansible_dev/collections']
DEFAULT_CALLBACK_WHITELIST(/runner/ansible.cfg) = ['ansible.posix.profile_tasks']
DEFAULT_HOST_LIST(/runner/ansible.cfg) = ['/runner/inventory']
DEFAULT_ROLES_PATH(/runner/ansible.cfg) = ['/home/runner/.ansible/roles', '/runner/project/ansible_dev/roles']
HOST_KEY_CHECKING(/runner/ansible.cfg) = False

```

##### ANSIBLE GALAXY INFO
```
# /runner/project/ansible_dev/collections/ansible_collections
Collection      Version
--------------- -------
cloudera.aux    0.0.1  
cloudera.cdp_dc 1.0.2  
cloudera.exe    0.0.1  
cloudera.mgmt   0.0.1  

# /home/runner/.ansible/collections/ansible_collections
Collection           Version
-------------------- -------
amazon.aws           1.4.0  
ansible.netcommon    1.5.0  
ansible.posix        1.1.1  
azure.azcollection   1.4.0  
community.aws        1.4.0  
community.crypto     1.4.0  
community.general    2.1.1  
community.mysql      1.2.0  
community.postgresql 1.1.1  
google.cloud         1.0.2  
netapp.azure         21.2.0 
```

##### Python Packages Info
```
adal==1.2.6
ansible-base @ file:///output/wheels/ansible_base-2.10.6.post0-py3-none-any.whl
ansible-runner @ file:///output/wheels/ansible_runner-2.0.0-py3-none-any.whl
appdirs==1.4.4
applicationinsights==0.11.9
argcomplete==1.12.2
asn1crypto==1.2.0
attrs==20.3.0
awscli==1.19.12
azure-cli-core==2.11.1
azure-cli-nspkg==3.0.2
azure-cli-telemetry==1.0.6
azure-common==1.1.11
azure-core==1.12.0b1
azure-graphrbac==0.61.1
azure-keyvault==1.0.0a1
azure-mgmt-authorization==0.51.1
azure-mgmt-automation==0.1.1
azure-mgmt-batch==5.0.1
azure-mgmt-cdn==3.0.0
azure-mgmt-compute==10.0.0
azure-mgmt-containerinstance==1.4.0
azure-mgmt-containerregistry==2.0.0
azure-mgmt-containerservice==9.1.0
azure-mgmt-core==1.2.0
azure-mgmt-cosmosdb==0.5.2
azure-mgmt-devtestlabs==3.0.0
azure-mgmt-dns==2.1.0
azure-mgmt-hdinsight==0.1.0
azure-mgmt-iothub==0.7.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-loganalytics==1.0.0
azure-mgmt-managedservices==1.0.0
azure-mgmt-marketplaceordering==0.1.0
azure-mgmt-monitor==0.5.2
azure-mgmt-netapp==1.0.0
azure-mgmt-network==10.2.0
azure-mgmt-nspkg==2.0.0
azure-mgmt-privatedns==0.1.0
azure-mgmt-rdbms==1.9.0
azure-mgmt-redis==5.0.0
azure-mgmt-resource==10.2.0
azure-mgmt-servicebus==0.5.3
azure-mgmt-sql==0.10.0
azure-mgmt-storage==11.1.0
azure-mgmt-trafficmanager==0.50.0
azure-mgmt-web==0.41.0
azure-nspkg==2.0.0
azure-storage==0.35.1
Babel==2.7.0
bcrypt==3.2.0
boto==2.49.0
boto3==1.17.12
botocore==1.20.12
cachetools==4.2.1
cdpcli-beta==0.9.26
cdpy==0.1.0
certifi==2020.12.5
cffi==1.13.2
chardet==4.0.0
colorama==0.3.9
cryptography==3.4.6
decorator==4.4.2
deepdiff==5.2.3
docutils==0.14
dogpile.cache==1.1.2
dumb-init==1.2.5
google-auth==1.27.0
humanfriendly==8.2
idna==2.8
iso8601==0.1.14
isodate==0.6.0
Jinja2==2.10.3
jmespath==0.10.0
jsonmerge==1.8.0
jsonpatch==1.28
jsonpointer==2.0
jsonschema==3.2.0
keystoneauth1==4.3.0
knack==0.7.2
lockfile==0.12.2
MarkupSafe==1.1.1
msal==1.0.0
msal-extensions==0.1.3
msrest==0.6.10
msrestazure==0.6.4
munch==2.5.0
netaddr==0.8.0
netifaces==0.10.9
oauthlib==3.1.0
openstacksdk==0.53.0
ordered-set==4.0.2
os-service-types==1.7.0
packaging==20.9
paramiko==2.7.2
pbr==5.5.1
pexpect==4.8.0
pkginfo==1.7.0
ply==3.11
portalocker==1.7.1
ptyprocess==0.7.0
pure25519==0.0.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.19
Pygments==2.8.0
PyJWT==1.7.1
PyNaCl==1.4.0
pyOpenSSL==20.0.1
pyparsing==2.4.7
pyrsistent==0.17.3
python-daemon==2.2.4
python-dateutil==2.8.1
pytz==2019.3
PyYAML==5.3.1
requests==2.25.1
requests-oauthlib==1.3.0
requestsexceptions==1.4.0
rsa==4.5
s3transfer==0.3.4
six==1.12.0
stevedore==3.3.0
tabulate==0.8.8
urllib3==1.26.3
xmltodict==0.12.0
```

##### PYTHON VERSION
```
Python 3.8.3
```

##### OS / ENVIRONMENT

Running in Centos8 Docker containers on Osx

##### STEPS TO REPRODUCE

```yaml
- name: Remove Azure NetApp Volume
  netapp.azure.azure_rm_netapp_volume:
    resource_group: "{{ infra__azure_metagroup_name }}"
    account_name: "{{ infra__azure_netapp_account_name }}"
    pool_name: "{{ infra__azure_netapp_pool_name }}"
    name: "{{ infra__azure_netapp_vol_name }}"
    state: absent
    location: "{{ infra__region }}"
```

##### EXPECTED RESULTS

Ansible should remove the volume or report none found

##### ACTUAL RESULTS

```paste below
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1613924655.2909138-430-187407053471073/AnsiballZ_azure_rm_netapp_volume.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1613924655.2909138-430-187407053471073/AnsiballZ_azure_rm_netapp_volume.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1613924655.2909138-430-187407053471073/AnsiballZ_azure_rm_netapp_volume.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.netapp.azure.plugins.modules.azure_rm_netapp_volume', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_netapp.azure.azure_rm_netapp_volume_payload_o4oxh6uy/ansible_netapp.azure.azure_rm_netapp_volume_payload.zip/ansible_collections/netapp/azure/plugins/modules/azure_rm_netapp_volume.py", line 318, in <module>
  File "/tmp/ansible_netapp.azure.azure_rm_netapp_volume_payload_o4oxh6uy/ansible_netapp.azure.azure_rm_netapp_volume_payload.zip/ansible_collections/netapp/azure/plugins/modules/azure_rm_netapp_volume.py", line 314, in main
  File "/tmp/ansible_netapp.azure.azure_rm_netapp_volume_payload_o4oxh6uy/ansible_netapp.azure.azure_rm_netapp_volume_payload.zip/ansible_collections/netapp/azure/plugins/modules/azure_rm_netapp_volume.py", line 193, in __init__
  File "/tmp/ansible_netapp.azure.azure_rm_netapp_volume_payload_o4oxh6uy/ansible_netapp.azure.azure_rm_netapp_volume_payload.zip/ansible_collections/netapp/azure/plugins/module_utils/azure_rm_netapp_common.py", line 28, in __init__
  File "/tmp/ansible_netapp.azure.azure_rm_netapp_volume_payload_o4oxh6uy/ansible_netapp.azure.azure_rm_netapp_volume_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 441, in __init__
  File "/tmp/ansible_netapp.azure.azure_rm_netapp_volume_payload_o4oxh6uy/ansible_netapp.azure.azure_rm_netapp_volume_payload.zip/ansible_collections/netapp/azure/plugins/modules/azure_rm_netapp_volume.py", line 289, in exec_module
  File "/tmp/ansible_netapp.azure.azure_rm_netapp_volume_payload_o4oxh6uy/ansible_netapp.azure.azure_rm_netapp_volume_payload.zip/ansible_collections/netapp/azure/plugins/modules/azure_rm_netapp_volume.py", line 201, in get_azure_netapp_volume
  File "/tmp/ansible_netapp.azure.azure_rm_netapp_volume_payload_o4oxh6uy/ansible_netapp.azure.azure_rm_netapp_volume_payload.zip/ansible_collections/netapp/azure/plugins/module_utils/azure_rm_netapp_common.py", line 35, in netapp_client
NameError: name 'AzureNetAppFilesManagementClient' is not defined

```

**Comment by lonico** [comment]
I'm not sure I understand why this is failing.  But I like your changes, and I'll make a change to report the import errors in the __init__ function.

**Comment by lonico** [comment]
I wonder if you initially updated modules without updating module_utils.  The line numbers (28 and 35) seem to indicate an older version of azure_rm_netapp_common.py.

**Comment by Chaffelson** [comment]
hmm, that's an interesting observation - I use a execution environment generator which attempts to consistently resolve all the dependencies for my deployment, but the python requirements for it are pretty straight forward so I'm not sure how it would get an older version of a particular file in the package.
https://github.com/cloudera-labs/ansible-runner/blob/devel/deps/python.txt

**Comment by lonico** [comment]
It does not show how the collection was installed.  Since the new changes are not available on Galaxy, they would have to come from GitHub.  But still concerning but something may be out of sync.  I'll check GitHub changelogs to be sure.

**Comment by Chaffelson** [comment]
@lonico ah interesting - I installed the collection via galaxy, but it's possible that I had not cleaned out my ansible install and was picking up a different version with the funky way it resolves which paths to use.
Thanks for merging, I'll use the main branch directly from github until a new version is released.
